name: "Publish to Sigrid (Marketplace)"
on:
  push:
    branches: [$default-branch]
jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
    - name: Sigrid CI
      uses: Software-Improvement-Group/sigridci@v1.1.0
      with:
        customer: "opensource"
        system: "cspacmandennis"
        targetquality: "3.5"
        publish: true
      env:
        SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
