name: "Publish to Sigrid (Marketplace)"
on: push
jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
    - name: Sigrid CI
      uses: Software-Improvement-Group/sigridci@v1.1.0
      with:
        customer: "opensource"
        system: "cspacman_dennis"
        targetquality: "3.7"
        publish: true
      env:
        SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
